### ISSUE TITLE
Not compatible with Slapper

### ISSUE THREAD

**Issue by jojoe77777** [LegoPlugins/SlapperKill#1]
Use "MushroomCow", "PigZombie", and "LavaSlime". I'm staying with those for multiple reasons.

**Comment by legoboy0215** [comment]
Why? Ok. I will fix it sir.

**Comment by legoboy0215** [comment]
Ummm... Care to help me edit?

**Comment by jojoe77777** [comment]
Sure. I didn't do it earlier because I was very laggy and could only get to this page.

**Comment by legoboy0215** [comment]
Me too... I think Github server had problems...
